# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code65wat', '0003_auto_20161222_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='attack_countdown',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 9, 1, 58, 930142)),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='messages',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='resource_x',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='resource_y',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='resource_z',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='upgrade_countdown',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 9, 1, 58, 930142)),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='upgrade_lvl',
            field=models.IntegerField(default=0),
        ),
    ]
