# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code65wat', '0004_auto_20161222_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 9, 7, 41, 623540)),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='attack_countdown',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 9, 7, 41, 623540)),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='upgrade_countdown',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 9, 7, 41, 623540)),
        ),
    ]
